typography_spectrum: 0.22932210184274113
color:
  brandStrength: 0.48052390414022716
  lightness: 0.30141590880460595
  saturation: 0.11064670164045869
  rhythmicContrast: 0.432767302213458
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
github: true
layout_spectrum: 0.6815958820718645
analytics:
  google: UA-98687120-5
name: Amazing World
url: 'https://amazingworld.only-amazing.com/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Amazing Tech
    url: 'http://amazingtech.only-amazing.com/'
    type: external
  - name: Amazing Science
    url: 'http://amazingscience.only-amazing.com/'
    type: external
  - name: Amazing People
    url: 'http://amazingpeople.only-amazing.com/'
    type: external
  - name: Amazing Experience
    url: 'http://amazingexperience.only-amazing.com/'
    type: external
  - name: Contact us
    url: 'http://only-amazing.com/onlyamazing-is-supported-by/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7e59070f-2f9d-46a1-86eb-eec438574f10.jpg
title: 'All of the #Amazing the world has to offer!'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FpHvmGucGm_E%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DpHvmGucGm_E&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FpHvmGucGm_E%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://www.youtube.com/watch?v=pHvmGucGm_E'
      keywords:
        - video
        - sharing
        - camera phone
        - video phone
        - free
        - upload
      related: []
      author:
        - name: Explore Bears & Bison
          url: 'https://www.youtube.com/channel/UC2Sk0aXLq3ADkH_USGPKT_Q'
          avatar: {}
      '@context': 'http://schema.org'
      title: 'Brooks Falls - Katmai National Park, Alaska powered by EXPLORE.org'
      '@type': VideoObject
      app_links: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      description: >-
        Explore Website: http://explore.org Facebook: http://goo.gl/SFRAfX -
        Twitter: http://goo.gl/n03NNU Watch Brooks Falls - Katmai National Park
        - LIVE You are watching exclusive LIVE footage from Alaska's Brooks
        River in Katmai National Park. Every year over a hundred Brown Bears
        descend on a mile long stretch of Brooks River to feast on the largest
        Sockeye Salmon run in the world.
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ' Enjoy this months live video is of the Brooks Falls in Katmai National Park'
