layout_spectrum: 0.6815958820718645
typography_spectrum: 0.22932210184274113
color:
  brandStrength: 0.48052390414022716
  lightness: 0.30141590880460595
  saturation: 0.11064670164045869
  rhythmicContrast: 0.432767302213458
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
name: Amazing World
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Home
    url: 'http://only-amazing.com/'
    type: external
title: '#AmazingWorld'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FpHvmGucGm_E%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DpHvmGucGm_E&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FpHvmGucGm_E%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Explore Bears & Bison
          url: 'https://www.youtube.com/channel/UC2Sk0aXLq3ADkH_USGPKT_Q'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      keywords:
        - video
        - sharing
        - camera phone
        - video phone
        - free
        - upload
      description: >-
        Explore Website: http://explore.org Facebook: http://goo.gl/SFRAfX -
        Twitter: http://goo.gl/n03NNU Watch Brooks Falls - Katmai National Park
        - LIVE You are watching exclusive LIVE footage from Alaska's Brooks
        River in Katmai National Park. Every year over a hundred Brown Bears
        descend on a mile long stretch of Brooks River to feast on the largest
        Sockeye Salmon run in the world.
      '@type': VideoObject
      app_links: []
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=pHvmGucGm_E'
      title: 'Brooks Falls - Katmai National Park, Alaska powered by EXPLORE.org'
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  All of the #Amazing the world has to offer! Enjoy this months live video is of
  the Brooks Falls in Katmai National Park
url: 'https://amazingworld.only-amazing.com/'
analytics:
  google: UA-98687120-5
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7e59070f-2f9d-46a1-86eb-eec438574f10.jpg
github: true
